### ISSUE TITLE
Bump Azure SDK

### ISSUE THREAD

**Issue by alexander-demicev** [rancher/aks-operator#132]
We should bump azure because we are using that might be deprecated in future https://github.com/rancher/aks-operator/pull/123

Migration docs https://github.com/Azure/azure-sdk-for-go

### PR's:
- [x] https://github.com/rancher/aks-operator/pull/447
- [x] https://github.com/rancher/rancher/pull/44928/
- [x] https://github.com/rancher/rancher/pull/45143

**Comment by kkaempf** [comment]
@alexander-demicev @mjura - this is a year old now - how urgent is this actually ?

**Comment by cpinjani** [comment]
The current milestone [v2.8-Next2](https://github.com/rancher/aks-operator/milestone/6) seems incorrect as corresponding PRs are merged to v2.9 branches. Changing it v2.9.0
cc: @kkaempf

**Comment by mjura** [comment]
@yiannistri can you please check why it is failing? thank you so much

**Comment by cpinjani** [comment]
Validated on build:
```
v2.9-6d87a11ea46b7571646d7c3d7af704584c39fd62-head
aks-operator:v1.3.0-rc12
```
P0 Checks are passing (tested via API), however UI bugs are blocking the full validation.
https://github.com/rancher/dashboard/issues/10966
https://github.com/rancher/dashboard/issues/10950

**Comment by cpinjani** [comment]
Validation passed :white_check_mark: 
```
Rancher - v2.9-4ac81b66b0f971548be78f2d1c72ecb906171a0b-head
Dashboard - master e750c25
aks-operator:v1.9.0-rc.6
```
