### ISSUE TITLE
Avoid caching secret

### ISSUE THREAD

**Issue by alexander-demicev** [rancher/aks-operator#159]
While writing tests I noticed that the [secret cache](https://github.com/rancher/aks-operator/blob/master/controller/aks-cluster-config-handler.go#L113) can return outdated data. Secrets are considered sensitive and we might want to always see the latest changes, I suggest disabling secrets caching.

### PR's:
- [x] https://github.com/rancher/eks-operator/pull/437
- [x] https://github.com/rancher/eks-operator/pull/468
- [x] https://github.com/rancher/rancher/pull/45139

**Comment by furkatgofurov7** [comment]
@alexander-demicev I can try to tackle this once we discuss about possible implications and way forward for how do you see it has to be handled. 

At high level, passing the secret cache and how it is handled in the `func Register()` seems to be inherited from original [rancher/wrangler] (https://github.com/rancher/wrangler/blob/39a4707f0689cc97ca955f5eea5d0b37e1664cae/pkg/needacert/needacert.go#L38-L51) package and used not only in this operator but [GKE](https://github.com/rancher/gke-operator/blob/7551c51645b9a0d1b42ec1250bbf24605883c104/controller/gke-cluster-config-handler.go#LL81C4-L81C36)/[EKS](https://github.com/rancher/eks-operator/blob/3b90eb73d6e03357f5d8243c590808428bdd4ef5/controller/eks-cluster-config-handler.go#L71) as well.
