### ISSUE TITLE
Custom AKS API calls for customer

### ISSUE THREAD

**Issue by kkaempf** [rancher/aks-operator#162]

**Comment by sowmyav27** [comment]
@kkaempf need more info for providing a QA LOE

**Comment by mjura** [comment]
I have add Confluence page https://confluence.suse.com/display/CAP/How+to+make+custom+Rancher+API+calls with

Documentation for custom Rancher API calls:
- Update AKS cluster version
- Update AKS min and max Count values for Node Pool
- Update AKS nodeLabels for Node Pool
- Update AKS nodeTaints for Node Pool
