### ISSUE TITLE
[Feature] K8s 1.26 support

### ISSUE THREAD

**Issue by kkaempf** [rancher/aks-operator#177]
See https://github.com/rancher/rancher/issues/41113

Verify that k8s 1.26 works with aks-operator.

Update charts accordingly.

**Comment by kkaempf** [comment]
> Both creating/importing existing AKS clusters with k8s version v1.26.3 worked fine:

Thanks ! I assume this issue can be closed then ?!

**Comment by furkatgofurov7** [comment]
> > Both creating/importing existing AKS clusters with k8s version v1.26.3 worked fine:
> 
> Thanks ! I assume this issue can be closed then ?!

Yes, I think so. Updating the charts [PR](https://github.com/rancher/charts/pull/2617) is also merged.
