### ISSUE TITLE
Cannot modify AKS if nodepool is == 12 chars long

### ISSUE THREAD

**Issue by kkaempf** [rancher/aks-operator#209]
### Issue description:
Microsoft describes as 1-12 characters long for it's linux nodepool as naming convention, whereas in Rancher the limit is 1-11 characters.

If you create a nodepool in Azure portal/Az cli (either system or user) 12 characters long, then the AKS configuration cannot be changed, due to triggering this Rancher nodepool naming limit.

### Business impact:
The AKS cluster is stuck and cannot be configured. The nodepools, or kubernetes version or any other configuration cannot be applied as always the "Linux node pool names must be 1-11 characters." is shown in the Rancher UI.

### Repro steps:

Create an AKS cluster from Rancher, and create an agent pool.
Create in the Azure portal a 2nd nodepool for the AKS cluster, with a name 12 characters long. Then, in Rancher console the cluster cannot be configured (change labels, upgrade the k8s version, add additional nodepools, change/remove current nodepools). 

### Workaround:
Is a workaround available and implemented? yes
What is the workaround: Create an additional nodepool 11chars long, and then delete the previous Nodepool with the 12chars-long name. 

### Actual behavior:
Nodepools created with a 12chars-long in AKS via Azure Portal (as Rancher does not allow it), provokes that the cluster configuration cannot be changed.

It can still be managed as a k8s cluster, deploy applications, storage, monitoring, create projects&namespaces, assign users as cluster Members / Cluster users / project Members / project Owners , and so on, but the Nodepools or any k8s version upgrade or cluster label update is not possible, all fail with the error "Linux node pool names must be 1-11 characters.")

### Expected behavior:
Nodepools in Rancher can be created with a 12 chars-long-name. Even creating a nodepool outside of Rancher (Azure portal or Az cli), if it has 12 characters long, the cluster is still manageable through Rancher.

Files, logs, traces:
Attached are screenshots of the bug.

### Additional notes:
https://learn.microsoft.com/en-us/azure/aks/use-multiple-node-pools#add-a-node-pool

https://learn.microsoft.com/en-us/azure/aks/use-system-pools?tabs=azure-cli#limitations

**Comment by furkatgofurov7** [comment]
This is interesting, I left a [comment](https://jira.suse.com/browse/SURE-6333?focusedCommentId=1267217&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-1267217) in the jira itself, and TL;DR is: this is a constraint coming from the Azure API itself and there is a low chance we can do something on either Rancher / AKS operator code, except fixing a warning message in UI (it should not be `1-11` but `1-12` characters long as per Azure error output: _"must be 12 or fewer characters"_)

**Comment by cpinjani** [comment]
Validated the fix on build:
```
Rancher- v2.7-58aede67b99fd5002cc44c2b36583834595acad2-head
Dashboard - master cb3162581
```
Nodepool validation is happening for 1-12 characters limit on UI. Also able to modify Nodepool configuration.
![image](https://github.com/rancher/aks-operator/assets/73099870/6bcb768d-6c51-4807-b892-a81f833d2b46)
