### ISSUE TITLE
Document AKSClusterConfig API type

### ISSUE THREAD

**Issue by richardcase** [rancher/aks-operator#238]
## SURE-5202

We need to document the [AKSClusterConfig](https://github.com/rancher/aks-operator/blob/master/pkg/apis/aks.cattle.io/v1/types.go#L26C6-L26C22) API type including all child file and structs with:

- documentation comments
- kubebuilder validation annotations

## PR's:

- [x] https://github.com/rancher/aks-operator/pull/247

**Comment by richardcase** [comment]
From the meeting just now, these are some of the additional links:

https://book.kubebuilder.io/reference/markers/crd-validation.html
https://github.com/rancher/rancher/blob/release/v2.8/pkg/apis/management.cattle.io/v3/cluster_types.go#L151-L153

**Comment by mjura** [comment]
fixed

**Comment by cpinjani** [comment]
Validated on nightly chart build:
![image](https://github.com/rancher/aks-operator/assets/73099870/d4ca6d62-8acc-428d-851a-5c0ef5346d5e)

Documentation not providing expected information, @mjura Can you please have a look ?

```
$ kubectl explain aksclusterconfigs.aks.cattle.io.spec.tags
GROUP:      aks.cattle.io
KIND:       AKSClusterConfig
VERSION:    v1

FIELD: tags <map[string]string>

DESCRIPTION:
    <empty>

```

**Comment by richardcase** [comment]
@cpinjani - we've only documented the structs/fields that are directly imported by Rancher. The `aksclusterconfigs.aks.cattle.io` kind is not designed to be directly used by end users so we didn't document it fully.

**Comment by cpinjani** [comment]
@richardcase Thanks for the clarification. Can this be closed as Done ?

**Comment by cpinjani** [comment]
Closing issue as discussed in standup, as current scope is met.
