### ISSUE TITLE
Unable to change Node pool mode

### ISSUE THREAD

**Issue by cpinjani** [rancher/aks-operator#249]
**Rancher version:**
```
v2.7-0b2f7fa0f878c3402ddf416a5b622327949b9348-head
aks-operator:v1.1.3-rc1
```
Cluster Type: Downstream AKS cluster

**Describe the bug**
In https://github.com/rancher/dashboard/issues/8105, user is now allowed to add new System/User node pool.
During edit of nodepools of an already running Active cluster, user can toggle mode of node pool from User to System and vice versa. But the operation is not succeeding.

**Screenshots**
![image](https://github.com/rancher/aks-operator/assets/73099870/0083751e-e2ae-40e1-a3bd-40c433bf5765)

Found while validating https://github.com/rancher/rancher/issues/42496

## PR's
- [x] https://github.com/rancher/aks-operator/pull/258
- [x] https://github.com/rancher/aks-operator/pull/257
- [x] https://github.com/rancher/aks-operator/pull/259

## Charts
- [ ] https://github.com/rancher/charts/pull/2912
- [ ] https://github.com/rancher/charts/pull/2911

**Comment by mjura** [comment]
I was able successfully reproduce this problem

**Comment by cpinjani** [comment]
Validated as fixed on build:
```
v2.7-9b00f7c784dfb7c9e908c04c9d93df33b2a10a76-head
aks-operator:v1.1.3-rc2
```

Test Results - :white_check_mark: 

Performed testing on Rancher provisioned downstream AKS cluster and Imported AKS cluster.

| Test Cases | 
| -- | 
| Change node pool mode from User to System|
| Change node pool mode from System to User |
| Change node pool mode on Azure AKS > Sync to Rancher |
| Upgrade cluster's k8s version and change pool mode  |
