### ISSUE TITLE
spec/aksConfig displaying null values for imported cluster

### ISSUE THREAD

**Issue by cpinjani** [rancher/aks-operator#251]
**Rancher version:**
```
v2.7-0b2f7fa0f878c3402ddf416a5b622327949b9348-head
aks-operator:v1.1.3-rc1
```

Cluster Type: Downstream AKS cluster
Issue also exists for other hosted providers.

**Describe the bug**
spec.aksConfig displaying null values for most the parameters for imported cluster
Values are being displayed after Editing cluster from UI

**Steps**
- Import Downstream AKS cluster in Rancher UI and wait for it to be Active
- Click 'View YAML' for the imported cluster

**Screenshots**
![image](https://github.com/rancher/aks-operator/assets/73099870/62b8593e-6a3c-4ecc-ada1-85825de2ea56)

After Edit cluster:
![image](https://github.com/rancher/aks-operator/assets/73099870/e852c4d3-9696-46b9-a261-d4c2690982c8)

Found while validating https://github.com/rancher/rancher/issues/42496

**Comment by richardcase** [comment]
Confirmed as a bug and the issue is with aks-operator

**Comment by cpinjani** [comment]
@kkaempf Can we please target this issue for next release ? It would simplify Back-end automation for Imported clusters.

**Comment by mjura** [comment]
@cpinjani @richardcase It is correct behavior, according to Rancher KEv2.

**Comment by mjura** [comment]
@cpinjani I have tested this once again. Everything is alright, we are using `null` values to check when managed cluster needs to be updated. For imported clusters we can update only settings for Node Pools.

So it is invalid
