### ISSUE TITLE
Add dependabot rule to ignore Wrangler

### ISSUE THREAD

**Issue by salasberryfin** [rancher/aks-operator#357]
### Description

`rancher/wrangler` versions are bumped manually so we should add an ignore rule to dependabot's configuration to avoid having PRs for new `wrangler` versions, as we do in other hosted providers, e.g. [gke-operator](https://github.com/rancher/gke-operator/blob/d6b7128cb64b1547e8a534dcc85854e445558c62/.github/dependabot.yaml#L24)

**Comment by mjura** [comment]
Change was already merge, we can resolve this PR
