### ISSUE TITLE
CI failing on API diff validation

### ISSUE THREAD

**Issue by salasberryfin** [rancher/aks-operator#359]
### Description

For the last couple of days we've had [API diff validation workflow failing on new PRs](https://github.com/rancher/aks-operator/actions/runs/7534808581/job/20509794469?pr=355).

After some investigation, it looks like this matches `joelanford/go-apidiff`'s new [release](https://github.com/joelanford/go-apidiff/releases). As we're using the latest version [here](https://github.com/rancher/aks-operator/blob/ba933df3b5b5fc12bb8a13963ae301f878af0c59/.github/workflows/apidiff.yaml#L14), CI is failing because our workflow is configured to use Go 1.18 while this new API diff action requires >1.19.

Updating the workflow's Go version to match the project's (Go 1.20) should fix this issue.

**Comment by mjura** [comment]
It will be suppressed by https://github.com/rancher/highlander/issues/89
