### ISSUE TITLE
[SURE-7299] Ability to edit rancher initiated helm jobs to apply a toleration so that they may target tainted nodes

### ISSUE THREAD

**Issue by kkaempf** [rancher/aks-operator#466]
### Problem statement
Any installation activity initiated from Rancher to downstream AKS cluster is creating a helm job initiated pod. Since these clusters has only tainted nodes, the helm initiated pods are in pending state and not able to get scheduled.

(Unable to schedule install jobs from rancher due to tainted nodes preventing helm from running due to an inability to edit rancher initiated helm jobs that communicate to downstream. )

**Comment by mjura** [comment]
Jira issue doesn't provide enough information on what is customer exception and what needs to be done. Taints are supported and applied properly by aks-operator. We have to wait until customer feedback.

**Comment by mjura** [comment]
Taints toleration for Rancher helm charts it is not Hosted operator issue.
