### ISSUE TITLE
[SURE-8291] AKS operator image doesn't get updated when switching to Prime

### ISSUE THREAD

**Issue by kkaempf** [rancher/aks-operator#482]
## SURE-8291
While doing a migration to Prime in 2.7.9 with CLAAS, we realized the operator gets upgraded if they are in use. If Rancher does not manage any more AKS or EKS clusters, then it is not upgraded with an image from the Prime registry.

### Request description:
Document the behavior of the AKS operator image when going to Prime. Same is valid for EKS.

### Actual behavior:
The operator gets upgraded if they are in use. If Rancher does not manage any more AKS or EKS clusters, then it is not upgraded.

### Expected behavior:
Not sure. Have to check what is the "right" behavior and simply have to document it what is expected and what not.

See JIRA for more details

### PR's:
- [ ] https://github.com/rancher/aks-operator/pull/491
- [ ] https://github.com/rancher/aks-operator/pull/492
- [ ] https://github.com/rancher/aks-operator/pull/493
- [ ] https://github.com/rancher/eks-operator/pull/508
- [ ] https://github.com/rancher/eks-operator/pull/509
- [ ] https://github.com/rancher/eks-operator/pull/510
- [ ] https://github.com/rancher/gke-operator/pull/447
- [ ] https://github.com/rancher/gke-operator/pull/448
- [ ] https://github.com/rancher/gke-operator/pull/449

**Comment by cpinjani** [comment]
Validated on build with prime staging registry, issue is still reproducing.
```
v2.9.0-alpha2
eks-operator:v1.9.0-rc.1
```
- Switch from community to prime staging while EKS cluster is running and set systemDefaultRegistry=stgregistry.suse.com while switching, eks-operator image switches to stgregistry.suse.com
![image](https://github.com/rancher/aks-operator/assets/73099870/12022907-3fd5-44db-b80f-3927ef1cb4b1)

- Switch from community to prime staging while no EKS cluster is running (operator is deployed)and set systemDefaultRegistry=stgregistry.suse.com while switching, eks-operator image does not switches to stgregistry.suse.com - :heavy_multiplication_x: 
![image](https://github.com/rancher/aks-operator/assets/73099870/ff3e6da2-307a-4d0e-af66-e1c6c26073e4)

**Comment by mjura** [comment]
@cpinjani it looks that there is problem somewhere in external migration script from Rancher which is not updating `systemDefaultRegistry=stgregistry.suse.com`. Could please let know what procedure did you use? Thank you

**Comment by mjura** [comment]
@cpinjani I have tested this scenario once again, according to https://github.com/rancher/rancher/blob/release/v2.9/pkg/controllers/dashboard/hostedcluster/controller.go#L80
Hosted operator will be upgraded as soon as there will be some cluster to manage, then version of helm charts will be checked and updated to the current supported version.

**Comment by mjura** [comment]
I am closing this issue
