### ISSUE TITLE
AKS: Subnet CIDR details not being displayed correctly

### ISSUE THREAD

**Issue by cpinjani** [rancher/aks-operator#574]
**Setup**
Rancher version: v2.7-0b2f7fa0f878c3402ddf416a5b622327949b9348-head
Browser type & version: Chrome latest

**Describe the bug**
Subnet CIDR details not being displayed as 'undefined'

**To Reproduce**
- Create downstream AKS cluster and select Network policy & Network plugin as Azure, under Networking
- Fill necessary fields and create clsuter 
- Wait for cluster to become Active
- Edit cluster and check Networking details

**Screenshots**
While cluster creation:
![image](https://github.com/rancher/dashboard/assets/73099870/6e3d51b1-a0e2-41b6-b1ef-a4ec45998bde)

Edit Cluster after creation:
![image](https://github.com/rancher/dashboard/assets/73099870/66e0ae87-b1ca-494c-8070-572d20f08b50)

Found while validating https://github.com/rancher/rancher/issues/42496

**Comment by cpinjani** [comment]
Transferred to rancher/aks-operator

**Comment by gaktive** [comment]
Removing from dashboard project for now. If UI is required, file a new ticket in our repo for tracking purposes.

**Comment by mjura** [comment]
After creating cluster values provided by users will be set as `null`, everything is correct.

This bug is invalid
