### ISSUE TITLE
Removing the only system nodepool from cluster via API does not show error 

### ISSUE THREAD

**Issue by valaparthvi** [rancher/aks-operator#619]
Rancher: v2.9-0d8af1460cfc73c3bf4bafecc38f399ea5c187a3-head
Dashboard: release-2.9 65f0232
Operator Version:  rancher-aks-operator:104.0.1+up1.9.0

Steps to reproduce:
1. Import a cluster with a single 'System' mode nodepool, and a user mode nodepool
2. Removing the 'System' mode nodepool via API
 
Result:
The update does not result in cluster to error out. 
The UI shows error 'At least 1 system nodepool is required, but there is no error in the operator logs or cluster object.

For a provisioned cluster, the operator logs and `cluster.Transitioning` and `cluster.TransitioningMessage` both show appropriate error messages.

![image](https://github.com/user-attachments/assets/7e5cbf62-2744-4f54-90ea-558dd7528b94)

![image](https://github.com/user-attachments/assets/e8e81532-0be6-413b-88c9-fd3fc1063256)

**PR's:**
- [x] https://github.com/rancher/aks-operator/pull/694

**Comment by cpinjani** [comment]
Validation passed on build: `v2.10-head, aks-operator:v1.10.0-rc.2`
Removing the only system nodepool from provisioned/imported cluster via API throws error

![image](https://github.com/user-attachments/assets/2fc62aca-e82f-4c95-8578-02b292043499)
