### ISSUE TITLE
(SURE-4131) Error handling and logging for creating AKS cluster without permissions to create tags

### ISSUE THREAD

**Issue by kkaempf** [rancher/aks-operator#92]
See also https://github.com/rancher/rancher/issues/36982

#### Issue description:
User attempted to create an AKS cluster with two tags. Appears user's account does not have permissions to create tags on an AKS cluster and rancher's aks operator was stuck in a loop retrying tag creating every 1-2 seconds.

#### Business impact:
No system feedback on why provisioning AKS cluster is stuck

#### Troubleshooting steps:
Viewed aks-config-operator logs (see attached)

#### Repro steps:

Create an AKS cluster, specify one or more tags. Make sure Azure account used does not have permissions to create tags on an AKS cluster.

#### Workaround:
Is workararound available and implemented? yes
What is the workaround: Manually add tags to the AKS cluster using the Azure portal or removing the tags from the AKS cluster on the rancher UI.

#### Actual behavior:
AKS cluster is stuck with waiting for provision, or also seeing this throttling error (likely due to aggressive attempts to update tags:

```
time="2022-02-21T23:10:00Z" level=error msg="error syncing 'cattle-global-data/c-w9h6r': handler aks-controller: containerservice.ManagedClustersClient#UpdateTags: Failure sending request: StatusCode=0 -- Original Error: Code=\"PatchResourceGroupError\" Message=\"Reconcile resource group failed with client error. Details: ResourceGroupReconciler retry failed: Category: ClientError; SubCode: SubscriptionRequestsThrottled; Dependency: Azure Resource Group; OrginalError: Code=\\\"SubscriptionRequestsThrottled\\\" Message=\\\"Number of write requests for subscription 'e7739666-3f36-4271-97ed-eff50e997132' exceeded the limit of '1200' for time interval '01:00:00'. Please try again after '303' seconds.\\\"; AKSTeam: Unknown, Retriable: false.\", requeuing"
```

Seeing continuous attempts to upgrade tags:
```
time="2022-02-22T00:19:31Z" level=info msg="Checking configuration for cluster [aks-dev-canadacentral]"
time="2022-02-22T00:19:32Z" level=info msg="Updating tags for cluster [aks-dev-canadacentral]"
time="2022-02-22T00:19:34Z" level=info msg="Checking configuration for cluster [aks-dev-canadacentral]"
time="2022-02-22T00:19:35Z" level=info msg="Updating tags for cluster [aks-dev-canadacentral]"
time="2022-02-22T00:19:37Z" level=info msg="Checking configuration for cluster [aks-dev-canadacentral]"
time="2022-02-22T00:19:38Z" level=info msg="Updating tags for cluster [aks-dev-canadacentral]"
```

#### Expected behavior:

aks-config-operator should log why it is not able to Update tags, if it failed
aks-config-operator can continue to re-attempt updating tags, but it should have an incremental backoff so it doesn't throttle the whole Azure subscription
An error should be propagated to the user UI. Something along the lines of - "Cluster could be provisioned. Failed to update tags. Error: <whatever Azure complains about>"

**Comment by alexander-demicev** [comment]
https://github.com/rancher/aks-operator/pull/70

**Comment by kkaempf** [comment]
PR #70 is merged. Can this issue here be closed then @alexander-demicev ?

**Comment by alexander-demicev** [comment]
Yes, we also included this change in the rancher charts already.
