### ISSUE TITLE
(SURE-5339) Upgrading downstream AKS clusters not working for both control plane and worker node pools.

### ISSUE THREAD

**Issue by kkaempf** [rancher/aks-operator#94]
### Issue description:

Upgrading downstream AKS clusters not working for both control plane and worker node pools

### Business impact:
Unable to upgrade downstream clusters means it can't follow along with release schedule

### Troubleshooting steps:
Re-create environment in AKS and import into Rancher

### Repro steps:

step 1: attempt to upgrade downstream 
step 2

### Workaround:
Is workararound available and implemented? no
What is the workaround: n/a

### Actual behavior:
Throws back errors due to not being able to fulfill a particular parameter

### Expected behavior:
Upgrade process completes successfully on downstream clusters

**Comment by mjura** [comment]
Problem https://jira.suse.com/browse/SURE-5537 is related to PepsiCO and really specific AKS cluster configuration, which we have fixed already in  https://jira.suse.com/browse/SURE-5339

I would wait until Rancher v2.7.2 with fix to SURE-5339 because for 99% it was fixed there.

**Comment by mjura** [comment]
it is was fixed in https://jira.suse.com/browse/SURE-5339 and wainting for v2.7.2 release and tested on customer env

**Comment by Sahota1225** [comment]
https://github.com/rancher/rancher/issues/40087#issuecomment-1475744269 - Same issue as this one and was validated by QA
